"""Alembic migration environment for AURALIS VISION.

This environment is wired to the application's configured database URL and to
the shared declarative ``Base.metadata`` so autogenerated migrations reflect the
ORM models (added in Task 1.4). The database URL is resolved through
:func:`app.database.get_database_url`, which reads it from application
configuration / the ``DATABASE_URL`` environment variable rather than from this
file, keeping secrets out of source (Requirement 25.5) and aligning migrations
with the runtime database (Requirement 26.1).
"""
from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Ensure the project root is importable so "app" resolves when Alembic runs.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from app.database import Base, get_database_url  # noqa: E402

# Import the models package so every model registers on ``Base.metadata``.
# It is imported defensively: the package exists now and is populated in
# Task 1.4, so autogeneration sees the full schema once models land.
try:  # pragma: no cover - import side effect only
    import app.models  # noqa: F401
except Exception:
    pass

# Alembic Config object providing access to alembic.ini values.
config = context.config

# Resolve the database URL from application configuration and hand it to Alembic.
config.set_main_option("sqlalchemy.url", get_database_url())

# Configure Python logging from the ini file when present.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Metadata used for 'autogenerate' support.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL without a DB connection)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live database connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
